Repository dtugroupd/RoomLocatorBackend, pull requests merged in 2019-11, with the labels that each got.

#37 Feature/download survey answers as csv
  RoomLocator/RoomLocator.Api/Controllers/SurveyController.cs
  RoomLocator/RoomLocator.Api/RoomLocator.Api.csproj
  RoomLocator/RoomLocator.Api/Startup.cs
  RoomLocator/RoomLocator.Data/RoomLocator.Data.csproj
  RoomLocator/RoomLocator.Data/Services/SurveyService.cs
  RoomLocator/RoomLocator.Domain/Config/AutoMapperConfigs/QuestionAnswerMapping.cs
  RoomLocator/RoomLocator.Domain/Config/AutoMapperConfigs/SurveyAnswerMapping.cs
  RoomLocator/RoomLocator.Domain/CsvModels/QuestionAnswerCsvModel.cs
  RoomLocator/RoomLocator.Domain/CsvModels/SurveyAnswerCsvModel.cs
  RoomLocator/RoomLocator.Domain/RoomLocator.Domain.csproj
Labels: backend, feature

#47 Fix user/me endpoint
  RoomLocator/RoomLocator.Api/Controllers/UserController.cs
Labels: bug

#49 Always make sure that MazeMapSections are seeded. Seed demo surveys o…
  RoomLocator/RoomLocator.Api/Helpers/DatabaseSeedHelper.cs
  RoomLocator/RoomLocator.Api/Startup.cs
Labels: backend

#53 Explicitly state comma separator in .csv
  RoomLocator/RoomLocator.Data/Services/SurveyService.cs
Labels: backend, bug

#56 Test Create in UserService
  RoomLocator/RoomLocator.UnitTest/BaseTest.cs
  RoomLocator/RoomLocator.UnitTest/RoomLocator.UnitTest.csproj
  RoomLocator/RoomLocator.UnitTest/Services/UserServiceTests.cs
Labels: test

#55 Return SurveyAnswer resource on create. Fix survey seed.
  RoomLocator/RoomLocator.Api/Controllers/SurveyController.cs
  RoomLocator/RoomLocator.Api/Helpers/DatabaseSeedHelper.cs
  RoomLocator/RoomLocator.Data/Services/SurveyService.cs
Labels: backend, bug

#70 Feature/role administration setup
  RoomLocator/RoomLocator.Api/Controllers/UserController.cs
  RoomLocator/RoomLocator.Data/Services/UserService.cs
  RoomLocator/RoomLocator.Domain/RoomLocator.Domain.csproj
Labels: backend, feature
